#!/bin/sh -
#Script to add chapter/TOC links at the beginning and end of each chapter.
#TOC name is TOC.htm, chapter files are chap$n.htm

toc=TOC.htm
tmpfile=tmp.htm

add_chap_anchors() {
	echo '<p><a href="'$toc'">Table of Contents</a>'
	[ -f $prevchap ] && \
		echo ' * <a href="'$prevchap'">Previous Chapter</a>'
	[ -f $nextchap ] && \
		echo ' * <a href="'$nextchap'">Next Chapter</a>'
	echo "<p>"
}

n=0
[ -f chap0.htm ] || n=1
thischap=chap$n.htm
while [ -f $thischap ]; do
	prevn=`expr $n - 1`
	prevchap=chap$prevn.htm
	nextn=`expr $n + 1`
	nextchap=chap$nextn.htm
	add_chap_anchors > $tmpfile
	cat $thischap >> $tmpfile
	add_chap_anchors >> $tmpfile
	mv $tmpfile $thischap
	n=$nextn
	thischap=chap$n.htm
done
exit 0
